### ISSUE TITLE
Device not created for pure event emitter

### ISSUE THREAD

**Issue by mbaran5** [jason0x43/hacs-hubitat#14]
I have two different button controllers in my setup, Xiaomi and Aeon. The Xiaomi works great in HA and shows all buttons plus battery state. I also have an Aeon Minimote that is not seen or added to HA

I’ve added it’s capabilities below Incase that helps. I notice it isn’t a “sensor” but it also doesn’t report battery life so not sure I expect to see that. 

I’m running your latest build and don’t see any error logs.

`[{"capabilities":["Configuration","Actuator","HoldableButton",{"attributes":[{"name":"held","currentValue":"1","dataType":"NUMBER","values":null}]},"PushableButton",{"attributes":[{"name":"numberOfButtons","currentValue":"4","dataType":"NUMBER","values":null},{"name":"pushed","currentValue":"2","dataType":"NUMBER","values":null}]}]}]`

**Comment by jason0x43** [comment]
Hmmm...I think I know what's happening there. Since the minimote has no sensors, no device is being created for it in Home Assistant. Even though events are probably being emitted in HA for button presses, it's hard to do much in HA without a device as a basis.

I need to update the code to create devices for pure event emitters (like the minimote).

**Comment by jason0x43** [comment]
This appears to be broken in 0.5.2. Reopening.

**Comment by jason0x43** [comment]
This is fixed in v0.5.3.

**Comment by mbaran5** [comment]
Thanks! I see the events being emitted now, but I still don't have a device. This is one of those pure emitters, no battery, sensors, or otherwise. It's an Aeon Minimote. Not sure if that's expected behavior. 

```
{
    "event_type": "hubitat_event",
    "data": {
        "device_id": "98",
        "device_name": "remote.bedroom",
        "attribute": "pushed",
        "value": "1",
        "description": "remote.bedroom button 1 was pushed",
        "type": "physical"
    },
    "origin": "LOCAL",
    "time_fired": "2020-05-26T02:47:04.567383+00:00",
    "context": {
        "id": "e397f0e8d9d74313a61d0a315e302d87",
        "parent_id": null,
        "user_id": null
    }
}
```
![image](https://user-images.githubusercontent.com/583865/82855824-339c9d00-9ec1-11ea-8537-7b75dd920b60.png)
